# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Francesco Laffi
email: francesco@laffi.io
description: >
  imported from wordpress to jekyll since its just an archive of old stuff,
  things are likely broken and will be unlikely fixed
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flweb.it" # the base hostname & protocol for your site
twitter_username: francescolaffi
github_username:  francescolaffi

# Build settings
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge
